# Generated by Django 4.0.3 on 2022-04-25 21:42

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'foguete'), ('lni-layers', 'design'), ('lni-cog', 'engrenagem'), ('lni-stats-up', 'grafico'), ('lni-mobile', 'mobile'), ('lni-users', 'clientes')], max_length=15, verbose_name='Icone'),
        ),
    ]
