# Generated by Django 4.0.3 on 2022-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem_alter_servico_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-layers', 'paginas'), ('lni-laptop-phone', 'dispositivo'), ('lni-leaf', 'folha'), ('lni-rocket', 'foguete'), ('lni-cog', 'engrenagem')], max_length=20, verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'clientes'), ('lni-stats-up', 'grafico'), ('lni-layers', 'design'), ('lni-mobile', 'mobile'), ('lni-cog', 'engrenagem'), ('lni-rocket', 'foguete')], max_length=15, verbose_name='Icone'),
        ),
    ]
