# Generated by Django 4.0.3 on 2022-05-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'paginas'), ('lni-laptop-phone', 'dispositivo'), ('lni-rocket', 'foguete'), ('lni-cog', 'engrenagem'), ('lni-leaf', 'folha')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'grafico'), ('lni-layers', 'design'), ('lni-rocket', 'foguete'), ('lni-users', 'clientes'), ('lni-cog', 'engrenagem'), ('lni-mobile', 'mobile')], max_length=15, verbose_name='Icone'),
        ),
    ]
